services:

  #Laravel Application
  app:
    build:
      context: .
      dockerfile: docker/dockerfiles/ssu.fpm.Dockerfile
      target: dev
      args:
        UID: ${UID}
        GID: ${GID}
        INSTALAR_SOAP: ${INSTALAR_SOAP}
        INSTALAR_GD: ${INSTALAR_GD}
        INSTALAR_IMAGICK: ${INSTALAR_IMAGICK}
        INSTALAR_BACKUP_TOOLS: ${INSTALAR_BACKUP_TOOLS}
    container_name: ${NAME}_app
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:8443"
    volumes:
      - ./code:/var/www/html
      - ./.agents:/var/www/html/.agents
      - ./.ai:/var/www/html/.ai
      - ./.github:/var/www/html/.github
      - ./.vscode:/var/www/html/.vscode
      - ./AGENTS.md:/var/www/html/AGENTS.md
    depends_on:
      - db
      - redis
    environment:
      PHP_OPCACHE_ENABLE: ${OPCACHE_ENABLE}
      SSL_MODE: "mixed"

  #Laravel Scheduler
  #  scheduler:
  #    build:
  #      context: .
  #      dockerfile: docker/dockerfiles/ssu.cli.Dockerfile
  #      target: scheduler
  #      args:
  #        UID: ${UID}
  #        GID: ${GID}
  #        INSTALAR_SOAP: ${INSTALAR_SOAP}
  #        INSTALAR_GD: ${INSTALAR_GD}
  #        INSTALAR_IMAGICK: ${INSTALAR_IMAGICK}
  #        INSTALAR_BACKUP_TOOLS: ${INSTALAR_BACKUP_TOOLS}
  #    container_name: ${NAME}_scheduler
  #    restart: unless-stopped
  #    volumes:
  #      - ./code:/var/www/html
  #    depends_on:
  #      - worker
  #      - db
  #      - redis
  #    environment:
  #      PHP_OPCACHE_ENABLE: ${OPCACHE_ENABLE}

  #Laravel Worker
  worker:
    build:
      context: .
      dockerfile: docker/dockerfiles/ssu.cli.Dockerfile
      target: worker
      args:
        UID: ${UID}
        GID: ${GID}
        INSTALAR_SOAP: ${INSTALAR_SOAP}
        INSTALAR_GD: ${INSTALAR_GD}
        INSTALAR_IMAGICK: ${INSTALAR_IMAGICK}
        INSTALAR_BACKUP_TOOLS: ${INSTALAR_BACKUP_TOOLS}
    container_name: ${NAME}_worker
    restart: unless-stopped
    volumes:
      - ./code:/var/www/html
    depends_on:
      - app
      - db
      - redis
    environment:
      PHP_OPCACHE_ENABLE: ${OPCACHE_ENABLE}

  #MARIA DB
  db:
    container_name: ${NAME}_db
    image: mariadb:11.4
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: unless-stopped
    user: ${UID}:${GID}
    ports:
      - "0.0.0.0:33061:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db
      MARIADB_PASSWORD: root

  #Redis
  redis:
    image: redis:alpine
    container_name: ${NAME}_redis
    restart: unless-stopped

  #Adminer - Alternativa a PHPMyAdmin
  adminer:
    image: adminer:4
    container_name: ${NAME}_adminer
    hostname: redis
    links:
      - db
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: ${NAME}_db
      ADMINER_DESIGN: 'dracula'
    restart: unless-stopped
    ports:
      - "0.0.0.0:81:8080"

  #Mailpit - Para pruebas de correo
  mailpit:
    image: axllent/mailpit
    container_name: ${NAME}_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      TZ: "America/Argentina/Buenos_Aires"

networks:
  default:
    name: ${NAME}_default
